name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
        npm install -g now
    - name: Deploy
      run: |
        now --token ${ZEIT}
      env:
        ZEIT: ${{ secrets.ZEIT }}
      
